# Generated by Django 3.1.2 on 2022-05-02 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=264)),
                ('adress', models.TextField(default='', max_length=264)),
            ],
            options={
                'verbose_name_plural': 'Video Libraries',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=264)),
                ('living_adress', models.TextField(max_length=264)),
                ('gender', models.CharField(max_length=264)),
                ('age', models.IntegerField()),
                ('staff_rating', models.IntegerField()),
                ('shop_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.videolibrary')),
            ],
            options={
                'verbose_name_plural': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(max_length=264)),
                ('staff_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.staff')),
            ],
            options={
                'verbose_name_plural': 'Ranks',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.IntegerField()),
                ('rank_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rank')),
            ],
            options={
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_amount', models.IntegerField()),
                ('shop_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.videolibrary')),
            ],
            options={
                'verbose_name_plural': 'Income',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=264, unique=True)),
                ('shop_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.videolibrary')),
            ],
            options={
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_name', models.CharField(max_length=264)),
                ('copies_amount', models.IntegerField()),
                ('film_cost', models.IntegerField()),
                ('genre_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.genre')),
                ('shop_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.videolibrary')),
            ],
            options={
                'verbose_name_plural': 'Films',
            },
        ),
        migrations.CreateModel(
            name='FilmReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_amount', models.IntegerField()),
                ('review_score', models.IntegerField()),
                ('film_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.films')),
            ],
            options={
                'verbose_name_plural': 'Film Reviews',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=264)),
                ('shop_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.videolibrary')),
            ],
            options={
                'verbose_name_plural': 'Equipment',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_amount', models.IntegerField()),
                ('shop_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.videolibrary')),
            ],
            options={
                'verbose_name_plural': 'Attendances',
            },
        ),
    ]
