# Generated by Django 3.1.2 on 2022-05-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220502_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_rating',
            field=models.IntegerField(),
        ),
    ]
